control:

  hold_time: 1
  sequence_step: 1

  distance:
    kp: 1.0
    ki: 0.0
    kd: 0.0
    lim_low: -2
    lim_high: 2

  distance_vel:
    kp: 0.1
    ki: 0.0
    kd: 0.0
    lim_low: -0.15
    lim_high: 0.15  
