control:

  rate: 50
  hover: 0.47

  ff_gain:
    velocity: 0.0
    acceleration: 0.0

  pos_x:  
    kp: 1.0
    ki: 0.0
    kd: 0.0
    lim_low: -15
    lim_high: 15
  
  vel_x:
    kp: 0.1
    ki: 0.0
    kd: 0.0
    lim_low: -0.4
    lim_high: 0.4  

  pos_y:
    kp: 1.0
    ki: 0.0
    kd: 0.0
    lim_low: -15
    lim_high: 15
   
  vel_y:
    kp: 0.1
    ki: 0.0
    kd: 0.0
    lim_low: -0.4
    lim_high: 0.4 

  pos_z:
    kp: 1.5
    ki: 0.1
    kd: 0.0
    lim_low: -15.0
    lim_high: 15.0

  vel_z:
    kp: 0.4
    ki: 0.0
    kd: 0.0
    lim_low: -0.5
    lim_high: 0.5  
