visual_servo:
  state_machine:
    
    rate: 50
    min_error: 0.5
    min_yaw_error: 0.05
    touchdown_height: 0.5
    touchdown_delta: 0.425
    touchdown_duration: 2
    after_touchdown_height: 3.1
    descent_speed: 0.2
    ascent_speed: 0.5
    detection_counter: 150
